# Generated by Django 6.0.2 on 2026-02-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField(default=0)),
                ('minutos_jugados', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='participacion',
            name='unique_jugador_partido',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='jugadores',
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='estadio',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='jornada',
        ),
        migrations.AddField(
            model_name='equipo',
            name='estadio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liga.estadio'),
        ),
        migrations.AddField(
            model_name='partido',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fundacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='competicion',
            name='equipos',
            field=models.ManyToManyField(blank=True, related_name='competiciones', to='liga.equipo'),
        ),
        migrations.AddField(
            model_name='estadisticajugador',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='liga.jugador'),
        ),
        migrations.AddField(
            model_name='estadisticajugador',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='liga.partido'),
        ),
        migrations.RemoveField(
            model_name='participacion',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='participacion',
            name='partido',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Participacion',
        ),
    ]
